version: '3.8'

services:
  app:
    build: ./backend
    container_name: node_app_fe
    restart: always
    ports:
      - '3000:3000'
    environment:
      - MONGOOSE_URL=mongodb://mongo:27077/mydb
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    container_name: mongodb_fe
    restart: always
    ports:
      - '27077:27017'
    volumes:
      - mongo-data:/data/db

  app_fe:
    build: ./frontend
    container_name: react_app_fe
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - app

volumes:
  mongo-data:
