version: '3.8'

services:
  app:
    build: ./backend
    container_name: node_app_fe
    restart: always
    ports:
      - '3011:3011'
    environment:
      - MONGOOSE_URL=mongodb://mongo:27017/mydb
      - PORT=3011
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    container_name: mongodb_fe
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
