version: '3.8'

services:
  app:
    build: ./backend
    container_name: node_app_fe
    restart: always
    ports:
      - '3011:3011'
    environment:
      - MONGOOSE_URL=mongodb://mongo:27017/mydb
      - PORT=3011
      - DEFAULT_OSMR_URL=http://osmr:5001
      - SPORT_OSMR_URL=http://osmr:5002
      - FAMILY_OSMR_URL=http://osmr:5003
    depends_on:
      - mongo
 
  mongo:
    image: mongo:7.0
    container_name: mongodb_fe
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  osmr:
    build: ./osrm
    container_name: osmr_basic_bicycle
    restart: always
    depends_on:
      - app
    ports:
      - '5001:5001'

  osmr-sport:
    build: ./osrm
    container_name: osmr_sport_bicycle
    restart: always
    depends_on:
      - app
    ports:
      - '5002:5002'

  osmr-family:
    build: ./osrm
    container_name: osmr_family_bicycle
    restart: always
    depends_on:
      - app
    ports:
      - '5003:5003'

volumes:
  mongo-data:
