version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: mongodb_dev
    restart: always
    ports:
      - '21370:27017'
    volumes:
      - mongo-dev-data:/data/db

volumes:
  mongo-dev-data:
